# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas-gois/Documents/structs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas-gois/Documents/structs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas-gois/Documents/structs/CMakeFiles /home/lucas-gois/Documents/structs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas-gois/Documents/structs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/lucas-gois/Documents/structs/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named entry

# Build rule for target.
entry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 entry
.PHONY : entry

# fast build rule for target.
entry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/build
.PHONY : entry/fast

algorithms/binary.o: algorithms/binary.cpp.o
.PHONY : algorithms/binary.o

# target to build an object file
algorithms/binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/binary.cpp.o
.PHONY : algorithms/binary.cpp.o

algorithms/binary.i: algorithms/binary.cpp.i
.PHONY : algorithms/binary.i

# target to preprocess a source file
algorithms/binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/binary.cpp.i
.PHONY : algorithms/binary.cpp.i

algorithms/binary.s: algorithms/binary.cpp.s
.PHONY : algorithms/binary.s

# target to generate assembly for a file
algorithms/binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/binary.cpp.s
.PHONY : algorithms/binary.cpp.s

algorithms/bubble.o: algorithms/bubble.cpp.o
.PHONY : algorithms/bubble.o

# target to build an object file
algorithms/bubble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/bubble.cpp.o
.PHONY : algorithms/bubble.cpp.o

algorithms/bubble.i: algorithms/bubble.cpp.i
.PHONY : algorithms/bubble.i

# target to preprocess a source file
algorithms/bubble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/bubble.cpp.i
.PHONY : algorithms/bubble.cpp.i

algorithms/bubble.s: algorithms/bubble.cpp.s
.PHONY : algorithms/bubble.s

# target to generate assembly for a file
algorithms/bubble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/bubble.cpp.s
.PHONY : algorithms/bubble.cpp.s

algorithms/insertion.o: algorithms/insertion.cpp.o
.PHONY : algorithms/insertion.o

# target to build an object file
algorithms/insertion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/insertion.cpp.o
.PHONY : algorithms/insertion.cpp.o

algorithms/insertion.i: algorithms/insertion.cpp.i
.PHONY : algorithms/insertion.i

# target to preprocess a source file
algorithms/insertion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/insertion.cpp.i
.PHONY : algorithms/insertion.cpp.i

algorithms/insertion.s: algorithms/insertion.cpp.s
.PHONY : algorithms/insertion.s

# target to generate assembly for a file
algorithms/insertion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/insertion.cpp.s
.PHONY : algorithms/insertion.cpp.s

algorithms/quick.o: algorithms/quick.cpp.o
.PHONY : algorithms/quick.o

# target to build an object file
algorithms/quick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/quick.cpp.o
.PHONY : algorithms/quick.cpp.o

algorithms/quick.i: algorithms/quick.cpp.i
.PHONY : algorithms/quick.i

# target to preprocess a source file
algorithms/quick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/quick.cpp.i
.PHONY : algorithms/quick.cpp.i

algorithms/quick.s: algorithms/quick.cpp.s
.PHONY : algorithms/quick.s

# target to generate assembly for a file
algorithms/quick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/quick.cpp.s
.PHONY : algorithms/quick.cpp.s

algorithms/selection.o: algorithms/selection.cpp.o
.PHONY : algorithms/selection.o

# target to build an object file
algorithms/selection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/selection.cpp.o
.PHONY : algorithms/selection.cpp.o

algorithms/selection.i: algorithms/selection.cpp.i
.PHONY : algorithms/selection.i

# target to preprocess a source file
algorithms/selection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/selection.cpp.i
.PHONY : algorithms/selection.cpp.i

algorithms/selection.s: algorithms/selection.cpp.s
.PHONY : algorithms/selection.s

# target to generate assembly for a file
algorithms/selection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/selection.cpp.s
.PHONY : algorithms/selection.cpp.s

algorithms/simple.o: algorithms/simple.cpp.o
.PHONY : algorithms/simple.o

# target to build an object file
algorithms/simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/simple.cpp.o
.PHONY : algorithms/simple.cpp.o

algorithms/simple.i: algorithms/simple.cpp.i
.PHONY : algorithms/simple.i

# target to preprocess a source file
algorithms/simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/simple.cpp.i
.PHONY : algorithms/simple.cpp.i

algorithms/simple.s: algorithms/simple.cpp.s
.PHONY : algorithms/simple.s

# target to generate assembly for a file
algorithms/simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/algorithms/simple.cpp.s
.PHONY : algorithms/simple.cpp.s

data_structures/queue.o: data_structures/queue.cpp.o
.PHONY : data_structures/queue.o

# target to build an object file
data_structures/queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/queue.cpp.o
.PHONY : data_structures/queue.cpp.o

data_structures/queue.i: data_structures/queue.cpp.i
.PHONY : data_structures/queue.i

# target to preprocess a source file
data_structures/queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/queue.cpp.i
.PHONY : data_structures/queue.cpp.i

data_structures/queue.s: data_structures/queue.cpp.s
.PHONY : data_structures/queue.s

# target to generate assembly for a file
data_structures/queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/queue.cpp.s
.PHONY : data_structures/queue.cpp.s

data_structures/stack.o: data_structures/stack.cpp.o
.PHONY : data_structures/stack.o

# target to build an object file
data_structures/stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/stack.cpp.o
.PHONY : data_structures/stack.cpp.o

data_structures/stack.i: data_structures/stack.cpp.i
.PHONY : data_structures/stack.i

# target to preprocess a source file
data_structures/stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/stack.cpp.i
.PHONY : data_structures/stack.cpp.i

data_structures/stack.s: data_structures/stack.cpp.s
.PHONY : data_structures/stack.s

# target to generate assembly for a file
data_structures/stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/data_structures/stack.cpp.s
.PHONY : data_structures/stack.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entry.dir/build.make CMakeFiles/entry.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... entry"
	@echo "... algorithms/binary.o"
	@echo "... algorithms/binary.i"
	@echo "... algorithms/binary.s"
	@echo "... algorithms/bubble.o"
	@echo "... algorithms/bubble.i"
	@echo "... algorithms/bubble.s"
	@echo "... algorithms/insertion.o"
	@echo "... algorithms/insertion.i"
	@echo "... algorithms/insertion.s"
	@echo "... algorithms/quick.o"
	@echo "... algorithms/quick.i"
	@echo "... algorithms/quick.s"
	@echo "... algorithms/selection.o"
	@echo "... algorithms/selection.i"
	@echo "... algorithms/selection.s"
	@echo "... algorithms/simple.o"
	@echo "... algorithms/simple.i"
	@echo "... algorithms/simple.s"
	@echo "... data_structures/queue.o"
	@echo "... data_structures/queue.i"
	@echo "... data_structures/queue.s"
	@echo "... data_structures/stack.o"
	@echo "... data_structures/stack.i"
	@echo "... data_structures/stack.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/lucas-gois/Documents/structs/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

